import os

from config import BASE_PATH


# Path
WAL_FPATH = os.path.join(BASE_PATH, "wal.log")
# Top level where each folder for each instrument's snapshots live
ENGINE_SNAPSHOT_FOLDER = os.path.join(BASE_PATH, "snapshots")
os.makedirs(ENGINE_SNAPSHOT_FOLDER, exist_ok=True)


# Redis
ENGINE_REDIS_DB = int(os.getenv("ENGINE_REDIS_DB"))
REDIS_CASH_BALANCE_PREFIX = os.getenv("REDIS_CASH_BALANCE_PREFIX")
REDIS_CASH_BALANCE_HKEY_PREFIX = os.getenv("REDIS_CASH_BALANCE_HKEY_PREFIX")
REDIS_CASH_ESCROW_PREFIX = os.getenv("REDIS_CASH_ESCROW_PREFIX")
REDIS_CASH_ESCROW_HKEY_PREFIX = os.getenv("REDIS_CASH_ESCROW_HKEY_PREFIX")
BACKUP_REDIS_HOST = os.getenv("BACKUP_REDIS_HOST")
BACKUP_REDIS_PORT = int(os.getenv("BACKUP_REDIS_PORT"))
BACKUP_REDIS_USERNAME = os.getenv("BACKUP_REDIS_USERNAME")
BACKUP_REDIS_PASSWORD = os.getenv("BACKUP_REDIS_PASSWORD")


# Kafka
# KAFKA_HOST = os.getenv("KAFKA_HOST")
# KAFKA_PORT = int(os.getenv("KAFKA_PORT"))
# KAFKA_BOOTSTRAP_SERVERS = f"{KAFKA_HOST}:{KAFKA_PORT}"
# KAFKA_COMMANDS_TOPIC = os.getenv("KAFKA_COMMANDS_TOPIC")
# KAFKA_BALANCE_EVENTS_TOPIC = os.getenv("KAFKA_BALANCE_EVENTS_TOPIC")
# KAFKA_ORDER_EVENTS_TOPIC = os.getenv("KAFKA_ORDER_EVENTS_TOPIC")
# KAFKA_TRADE_EVENTS_TOPIC = os.getenv("KAFKA_TRADE_EVENTS_TOPIC")
# KAFKA_INSTRUMENT_EVENTS_TOPIC = os.getenv("KAFKA_INSTRUMENT_EVENTS_TOPIC")


# Services
HEARTBEAT_LISTENER_HOST = os.getenv("HEARTBEAT_LISTENER_HOST")
HEARTBEAT_LISTENER_PORT = int(os.getenv("HEARTBEAT_LISTENER_PORT"))
HEARTBEAT_INTERVAL = 1.0
HEARTBEAT_STALE_THRESHOLD = 10.0
HEARTBEAT_CONNECT_TIMEOUT = 30.0


# Misc
SYSTEM_USER_ID = "4e10429f-6331-44a5-8fc5-118c1a976507"