import os


# Redis
ENGINE_REDIS_DB = int(os.getenv("ENGINE_REDIS_DB"))
REDIS_CASH_BALANCE_PREFIX = os.getenv("REDIS_CASH_BALANCE_PREFIX")
REDIS_CASH_BALANCE_HKEY_PREFIX = os.getenv("REDIS_CASH_BALANCE_HKEY_PREFIX")
REDIS_CASH_ESCROW_PREFIX = os.getenv("REDIS_CASH_ESCROW_PREFIX")
REDIS_CASH_ESCROW_HKEY_PREFIX = os.getenv("REDIS_CASH_ESCROW_HKEY_PREFIX")


SYSTEM_USER_ID = os.getenv("SYSTEM_USER_ID")
