"""added strategyt type field to orders

Revision ID: 2d5aa5a8f464
Revises: bedea2967feb
Create Date: 2026-01-13 09:39:01.355261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d5aa5a8f464'
down_revision: Union[str, Sequence[str], None] = 'bedea2967feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('strategy_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'strategy_type')
    # ### end Alembic commands ###
