"""added event type field to event_logs

Revision ID: 3a4dbe1018bd
Revises: 0f93628573f7
Create Date: 2025-11-30 19:52:59.184386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a4dbe1018bd'
down_revision: Union[str, Sequence[str], None] = '0f93628573f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_logs', sa.Column('event_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_logs', 'event_type')
    # ### end Alembic commands ###
