"""added primary key to asset_balances

Revision ID: 59af04eec715
Revises: 637826414adc
Create Date: 2025-12-15 21:51:44.853186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59af04eec715'
down_revision: Union[str, Sequence[str], None] = '637826414adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_balances', sa.Column('asset_balance_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_balances', 'asset_balance_id')
    # ### end Alembic commands ###
