"""x

Revision ID: 637826414adc
Revises: 3a4dbe1018bd
Create Date: 2025-11-30 23:13:18.713219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637826414adc'
down_revision: Union[str, Sequence[str], None] = '3a4dbe1018bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_balances', sa.Column('symbol', sa.String(), nullable=False))
    op.drop_index(op.f('ix_asset_balances_instrument_id'), table_name='asset_balances')
    op.drop_constraint(op.f('asset_balances_instrument_id_fkey'), 'asset_balances', type_='foreignkey')
    op.drop_column('asset_balances', 'instrument_id')
    op.add_column('engine_context_snapshots', sa.Column('symbol', sa.String(), nullable=False))
    op.drop_index(op.f('ix_engine_context_snapshots_instrument_id'), table_name='engine_context_snapshots')
    op.drop_constraint(op.f('engine_context_snapshots_instrument_id_fkey'), 'engine_context_snapshots', type_='foreignkey')
    op.drop_column('engine_context_snapshots', 'instrument_id')
    op.drop_constraint(op.f('instruments_symbol_key'), 'instruments', type_='unique')
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=True)
    op.add_column('orders', sa.Column('symbol', sa.String(), nullable=False))
    op.drop_constraint(op.f('orders_instrument_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'instrument_id')
    op.add_column('trades', sa.Column('symbol', sa.String(), nullable=False))
    op.drop_constraint(op.f('trades_instrument_id_fkey'), 'trades', type_='foreignkey')
    op.drop_column('trades', 'instrument_id')
    op.add_column('transactions', sa.Column('transaction_type', sa.String(), nullable=False))
    op.drop_column('transactions', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'transaction_type')
    op.add_column('trades', sa.Column('instrument_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('trades_instrument_id_fkey'), 'trades', 'instruments', ['instrument_id'], ['instrument_id'])
    op.drop_column('trades', 'symbol')
    op.add_column('orders', sa.Column('instrument_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('orders_instrument_id_fkey'), 'orders', 'instruments', ['instrument_id'], ['instrument_id'])
    op.drop_column('orders', 'symbol')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.create_unique_constraint(op.f('instruments_symbol_key'), 'instruments', ['symbol'], postgresql_nulls_not_distinct=False)
    op.add_column('engine_context_snapshots', sa.Column('instrument_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('engine_context_snapshots_instrument_id_fkey'), 'engine_context_snapshots', 'instruments', ['instrument_id'], ['instrument_id'])
    op.create_index(op.f('ix_engine_context_snapshots_instrument_id'), 'engine_context_snapshots', ['instrument_id'], unique=False)
    op.drop_column('engine_context_snapshots', 'symbol')
    op.add_column('asset_balances', sa.Column('instrument_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('asset_balances_instrument_id_fkey'), 'asset_balances', 'instruments', ['instrument_id'], ['instrument_id'])
    op.create_index(op.f('ix_asset_balances_instrument_id'), 'asset_balances', ['instrument_id'], unique=False)
    op.drop_column('asset_balances', 'symbol')
    # ### end Alembic commands ###
