"""Added escrow_balance field to asset_balances

Revision ID: 712e5163e3a9
Revises: ffa32df19b03
Create Date: 2026-01-31 11:43:38.530071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712e5163e3a9'
down_revision: Union[str, Sequence[str], None] = 'ffa32df19b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_balances', sa.Column('escrow_balance', sa.Float(), nullable=False, server_default=sa.text("0.0")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_balances', 'escrow_balance')
    # ### end Alembic commands ###
