"""x

Revision ID: 7b8e069d1969
Revises: 0339759e0561
Create Date: 2025-08-16 19:59:47.187832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8e069d1969'
down_revision: Union[str, Sequence[str], None] = '0339759e0561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('starting_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'starting_price')
    # ### end Alembic commands ###
