"""
Updated balance fields in asset balance to Numeric(12, 2)

Revision ID: 8d4f76bd8270
Revises: 59af04eec715
Create Date: 2025-12-24 12:02:39.353940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4f76bd8270'
down_revision: Union[str, Sequence[str], None] = '59af04eec715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_balances', 'balance',
               existing_type=sa.NUMERIC(precision=2, scale=2),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('asset_balances', 'escrow_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.drop_constraint(op.f('event_logs_event_id_key'), 'event_logs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('event_logs_event_id_key'), 'event_logs', ['event_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('asset_balances', 'escrow_balance',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('asset_balances', 'balance',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.NUMERIC(precision=2, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
