"""
Created engine snapshots table

Revision ID: 903101c815b4
Revises: 2b6468760a49
Create Date: 2025-11-29 19:40:37.128140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '903101c815b4'
down_revision: Union[str, Sequence[str], None] = '2b6468760a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_snapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_engine_snapshots_instrument_id'), 'engine_snapshots', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_asset_balances_instrument_id'), 'asset_balances', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_balances_instrument_id'), table_name='asset_balances')
    op.drop_index(op.f('ix_engine_snapshots_instrument_id'), table_name='engine_snapshots')
    op.drop_table('engine_snapshots')
    # ### end Alembic commands ###
