"""Added kafka metadata columns to engine context snapshots

Revision ID: a332f2026f22
Revises: bf91e6ad1f4e
Create Date: 2026-01-09 19:49:12.901865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a332f2026f22'
down_revision: Union[str, Sequence[str], None] = 'bf91e6ad1f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engine_context_snapshots', sa.Column('topic', sa.String(), nullable=False))
    op.add_column('engine_context_snapshots', sa.Column('partition', sa.BigInteger(), nullable=False))
    op.add_column('engine_context_snapshots', sa.Column('offset', sa.BigInteger(), nullable=False))
    op.add_column('engine_context_snapshots', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engine_context_snapshots', 'created_at')
    op.drop_column('engine_context_snapshots', 'offset')
    op.drop_column('engine_context_snapshots', 'partition')
    op.drop_column('engine_context_snapshots', 'topic')
    # ### end Alembic commands ###
