"""x

Revision ID: a97154995183
Revises: ef8efbbf6070
Create Date: 2025-11-28 23:10:11.514157

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a97154995183"
down_revision: Union[str, Sequence[str], None] = "ef8efbbf6070"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "autenticated_at")
    op.add_column(
        "users",
        sa.Column("authenticated_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "autenticated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.BOOLEAN(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
