"""Added order events table

Revision ID: bedea2967feb
Revises: a332f2026f22
Create Date: 2026-01-11 08:35:27.278275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bedea2967feb'
down_revision: Union[str, Sequence[str], None] = 'a332f2026f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('command_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_order_events_command_id'), 'order_events', ['command_id'], unique=False)
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_events_type'), 'order_events', ['type'], unique=False)
    op.drop_table('trades')
    op.drop_table('asset_balances')
    op.drop_table('transactions')
    op.add_column('event_logs', sa.Column('log_id', sa.UUID(), nullable=False))
    op.add_column('event_logs', sa.Column('type', sa.String(), nullable=False))
    op.alter_column('event_logs', 'timestamp',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('event_logs', 'data')
    op.drop_column('event_logs', 'event_type')
    op.drop_column('orders', 'group_type')
    op.drop_column('users', 'cash_balance')
    op.drop_column('users', 'escrow_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('escrow_balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('cash_balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('group_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_logs', sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('event_logs', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('event_logs', 'timestamp',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('event_logs', 'type')
    op.drop_column('event_logs', 'log_id')
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('related_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('transactions_user_id_fkey')),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('transactions_pkey'))
    )
    op.create_table('asset_balances',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('escrow_balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('asset_balance_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('asset_balances_user_id_fkey')),
    sa.PrimaryKeyConstraint('asset_balance_id', name=op.f('asset_balances_pkey'))
    )
    op.create_table('trades',
    sa.Column('trade_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('executed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('trades_order_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('trades_user_id_fkey')),
    sa.PrimaryKeyConstraint('trade_id', name=op.f('trades_pkey'))
    )
    op.drop_index(op.f('ix_order_events_type'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_command_id'), table_name='order_events')
    op.drop_table('order_events')
    # ### end Alembic commands ###
