"""
Updated balance fields in users to Numeric(12, 2)

Revision ID: bf91e6ad1f4e
Revises: 8d4f76bd8270
Create Date: 2025-12-24 12:12:58.960939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf91e6ad1f4e'
down_revision: Union[str, Sequence[str], None] = '8d4f76bd8270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'cash_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('users', 'escrow_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'escrow_balance',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('users', 'cash_balance',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
