"""x

Revision ID: dc70ba3669bd
Revises: 903101c815b4
Create Date: 2025-11-29 19:51:28.570177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc70ba3669bd'
down_revision: Union[str, Sequence[str], None] = '903101c815b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_context_snapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_engine_context_snapshots_instrument_id'), 'engine_context_snapshots', ['instrument_id'], unique=False)
    op.drop_index(op.f('ix_engine_snapshots_instrument_id'), table_name='engine_snapshots')
    op.drop_table('engine_snapshots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_snapshots',
    sa.Column('snapshot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('instrument_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], name=op.f('engine_snapshots_instrument_id_fkey')),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('engine_snapshots_pkey'))
    )
    op.create_index(op.f('ix_engine_snapshots_instrument_id'), 'engine_snapshots', ['instrument_id'], unique=False)
    op.drop_index(op.f('ix_engine_context_snapshots_instrument_id'), table_name='engine_context_snapshots')
    op.drop_table('engine_context_snapshots')
    # ### end Alembic commands ###
