"""
Drop events table;
Add order_group_id and parent_id to orders;
Dropped liquidty field from trades;
Added role field to trades;

Revision ID: ef8efbbf6070
Revises: 53ab629f9918
Create Date: 2025-11-28 17:09:26.465417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef8efbbf6070'
down_revision: Union[str, Sequence[str], None] = '53ab629f9918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.add_column('orders', sa.Column('order_group_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('parent_order_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('group_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_order_group_id'), 'orders', ['order_group_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'orders', ['parent_order_id'], ['order_id'])
    op.drop_column('orders', 'price')
    op.drop_column('orders', 'time_in_force')
    op.add_column('trades', sa.Column('role', sa.String(), nullable=False))
    op.drop_column('trades', 'liquidity')
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('autenticated_at', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'autenticated_at')
    op.drop_column('users', 'api_key')
    op.drop_column('users', 'email')
    op.add_column('trades', sa.Column('liquidity', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('trades', 'role')
    op.add_column('orders', sa.Column('time_in_force', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_order_group_id'), table_name='orders')
    op.drop_column('orders', 'group_type')
    op.drop_column('orders', 'parent_order_id')
    op.drop_column('orders', 'order_group_id')
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('related_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('events_user_id_fkey')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('events_pkey'))
    )
    # ### end Alembic commands ###
