"""
Added unique constraint to event_logs.event_id

Revision ID: f461fc47194c
Revises: dc70ba3669bd
Create Date: 2025-11-29 22:46:47.615256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f461fc47194c'
down_revision: Union[str, Sequence[str], None] = 'dc70ba3669bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event_logs', ['event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_logs', type_='unique')
    # ### end Alembic commands ###
