"""Added asset_balances table

Revision ID: ffa32df19b03
Revises: 2d5aa5a8f464
Create Date: 2026-01-29 17:36:13.008541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffa32df19b03'
down_revision: Union[str, Sequence[str], None] = '2d5aa5a8f464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlc',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ohlc_symbol'), 'ohlc', ['symbol'], unique=False)
    op.create_index(op.f('ix_ohlc_timeframe'), 'ohlc', ['timeframe'], unique=False)
    op.create_index(op.f('ix_ohlc_timestamp'), 'ohlc', ['timestamp'], unique=False)
    op.create_table('asset_balances',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'user_id')
    )
    op.create_table('balance_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('command_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_balance_events_command_id'), 'balance_events', ['command_id'], unique=False)
    op.create_index(op.f('ix_balance_events_symbol'), 'balance_events', ['symbol'], unique=False)
    op.create_index(op.f('ix_balance_events_timestamp'), 'balance_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_balance_events_type'), 'balance_events', ['type'], unique=False)
    op.create_index(op.f('ix_balance_events_user_id'), 'balance_events', ['user_id'], unique=False)
    op.add_column('order_events', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('order_events', sa.Column('symbol', sa.String(), nullable=False))
    op.create_index(op.f('ix_order_events_symbol'), 'order_events', ['symbol'], unique=False)
    op.create_index(op.f('ix_order_events_timestamp'), 'order_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_order_events_user_id'), 'order_events', ['user_id'], unique=False)
    op.create_foreign_key(None, 'order_events', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_events', type_='foreignkey')
    op.drop_index(op.f('ix_order_events_user_id'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_timestamp'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_symbol'), table_name='order_events')
    op.drop_column('order_events', 'symbol')
    op.drop_column('order_events', 'user_id')
    op.drop_index(op.f('ix_balance_events_user_id'), table_name='balance_events')
    op.drop_index(op.f('ix_balance_events_type'), table_name='balance_events')
    op.drop_index(op.f('ix_balance_events_timestamp'), table_name='balance_events')
    op.drop_index(op.f('ix_balance_events_symbol'), table_name='balance_events')
    op.drop_index(op.f('ix_balance_events_command_id'), table_name='balance_events')
    op.drop_table('balance_events')
    op.drop_table('asset_balances')
    op.drop_index(op.f('ix_ohlc_timestamp'), table_name='ohlc')
    op.drop_index(op.f('ix_ohlc_timeframe'), table_name='ohlc')
    op.drop_index(op.f('ix_ohlc_symbol'), table_name='ohlc')
    op.drop_table('ohlc')
    # ### end Alembic commands ###
